name: esurfing_client
description: Guangdong Tianyi Campus Network Authentication Client (Flutter + NDK FFI)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  connectivity_plus: ^6.0.3
  path_provider: ^2.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true